In [1]:
data = [
    (101, "Aarav Mehta", 50000, "HR"),
    (102, "Priya Sharma", 51000, "HR"),
    (103, "Rohan Verma", 51000, "HR"),
    (104, "Neha Patel", 53000, "HR"),
    (105, "Ankit Singh", 70000, "IT"),
    (106, "Kavya Iyer", 72000, "IT"),
    (107, "Rahul Nair", 71000, "IT"),
    (108, "Sneha Reddy", 73000, "IT"),
    (109, "Vikram Desai", 60000, "Finance"),
    (110, "Isha Malhotra", 62000, "Finance"),
    (111, "Siddharth Rao", 61000, "Finance"),
    (112, "Pooja Das", 63000, "Finance"),
    (113, "Manish Joshi", 55000, "Marketing"),
    (114, "Tanya Kapoor", 57000, "Marketing"),
    (115, "Harsh Sinha", 56000, "Marketing"),
    (116, "Divya Jain", 58000, "Marketing")
]
 
columns = ["emp_id", "emp_name", "emp_salary", "department"]

df = spark.createDataFrame(data, schema=columns)
df.createOrReplaceTempView("a")

StatementMeta(, cfe2aeb2-cbf6-436d-90a2-0f5a9304784e, 3, Finished, Available, Finished)

Cache file does not exists. resource=$ml, path=$/nfs4/tridenttokenlibrary/tokens/ml.token
failed to get ml token
Traceback (most recent call last):
  File "/home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages/synapse/ml/fabric/token_utils.py", line 156, in _get_access_token_from_token_lib
    return PyTridentTokenLibrary.get_access_token_from_cache(resource)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages/trident_token_library_wrapper.py", line 71, in get_access_token_from_cache
    raise IOError(err_msg)
OSError: Cache file does not exists. resource=$ml, path=$/nfs4/tridenttokenlibrary/tokens/ml.token

In [2]:
%%sql

select * 
from a

StatementMeta(, 7f43af92-79b7-4fcf-95db-84c889ee8441, 4, Finished, Available, Finished)

In [3]:
%%sql
select *
from 
    (select * , row_number() over(PARTITION by department order by emp_salary desc) as rn
    from a) b 
where b.rn=1

StatementMeta(, 1a6160a3-9abc-4f5a-89ee-9d15f84069d9, 5, Finished, Available, Finished)

In [5]:
%%sql
with 
aa as (select department,  min(emp_salary) from a group by department),

b as (select * from aa),
c as (select * from b)
select * from b;

WITH
x (select * from a)
select * from x;

StatementMeta(, 1a6160a3-9abc-4f5a-89ee-9d15f84069d9, 9, Finished, Available, Finished)

In [21]:
%%sql
select * 
    , row_number() over(order by emp_salary desc) as rn1
    , row_number() over(PARTITION by department order by emp_salary desc) as rn2
    , row_number() over(PARTITION by emp_salary order by department desc) as rn3
    , row_number() over(PARTITION by emp_salary order by department desc rows between unbounded preceding and current row) as rn4
    , row_number() over(PARTITION by department order by emp_salary desc rows between unbounded preceding and current row) as rn4
    -- , row_number() over(PARTITION by department order by emp_salary desc rows between unbounded preceding and unbounded FOLLOWING) as rn4
from a

StatementMeta(, 1a6160a3-9abc-4f5a-89ee-9d15f84069d9, 25, Finished, Available, Finished)

In [7]:
%%sql
select * 
    -- , rank() over() as rn1
    -- , rank() over(order by emp_salary) as rank1
    , row_number() over(order by emp_salary desc) as rn
    , rank() over(order by emp_salary desc) as rank
    , dense_rank() over(order by emp_salary desc) as dense_rank
    -- , row_number() over(PARTITION by department order by emp_salary desc) as rn2
    -- , row_number() over(PARTITION by emp_salary order by department desc) as rn3
    -- , row_number() over(PARTITION by emp_salary order by department desc rows between unbounded preceding and current row) as rn4
    -- , row_number() over(PARTITION by department order by emp_salary desc rows between unbounded preceding and current row) as rn4
    -- , row_number() over(PARTITION by department order by emp_salary desc rows between unbounded preceding and unbounded FOLLOWING) as rn4
from a

StatementMeta(, 4dcb3ff2-81ba-4cad-aedc-09c581e0bfb4, 9, Finished, Available, Finished)

In [1]:
data = [
    (101, "Aarav Mehta", 50000, "HR"),
    (102, "Priya Sharma", 50000, "HR"),
    (103, "Rohan Verma", 50000, "HR"),
    (104, "Neha Patel", 50000, "HR"),
    (105, "Ankit Singh", 70000, "IT"),
    (106, "Kavya Iyer", 70000, "IT"),
    (107, "Rahul Nair", 70000, "IT"),
    (108, "Sneha Reddy", 70000, "IT")
]
 
columns = ["emp_id", "emp_name", "emp_salary", "department"]

df = spark.createDataFrame(data, schema=columns)
df.createOrReplaceTempView("a")

StatementMeta(, 7b799ed7-92e5-4926-8877-60c0e3a75c21, 3, Finished, Available, Finished)

Cache file does not exists. resource=$ml, path=$/nfs4/tridenttokenlibrary/tokens/ml.token
failed to get ml token
Traceback (most recent call last):
  File "/home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages/synapse/ml/fabric/token_utils.py", line 156, in _get_access_token_from_token_lib
    return PyTridentTokenLibrary.get_access_token_from_cache(resource)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages/trident_token_library_wrapper.py", line 71, in get_access_token_from_cache
    raise IOError(err_msg)
OSError: Cache file does not exists. resource=$ml, path=$/nfs4/tridenttokenlibrary/tokens/ml.token

In [3]:
%%sql
select * 
    , row_number() over(order by emp_salary desc) as rn
    , rank() over(order by emp_salary desc) as rank
    , dense_rank() over(order by emp_salary desc) as dense_rank
from a

StatementMeta(, cfe2aeb2-cbf6-436d-90a2-0f5a9304784e, 5, Finished, Available, Finished)

In [20]:
%%sql
select 
        department
        ,emp_id
        ,lag(emp_id)over(partition by department order by emp_id) as lag1asc
        -- ,lag(emp_id,2)over(partition by department order by emp_id desc) as lag2desc 
        -- ,lead(emp_id,2)over(partition by department order by emp_id) as lead2asc

--  emp_id,lag(emp_id,1)over(order by emp_id) as lag 
    -- , row_number() over(order by emp_salary desc) as rn
    -- , rank() over(order by emp_salary desc) as rank
    -- , dense_rank() over(order by emp_salary desc) as dense_rank
from a
order by 1,2,3

StatementMeta(, cfe2aeb2-cbf6-436d-90a2-0f5a9304784e, 22, Finished, Available, Finished)

In [21]:
%%sql
select emp_id,max(emp_salary) over() as max
from a

StatementMeta(, cfe2aeb2-cbf6-436d-90a2-0f5a9304784e, 23, Finished, Available, Finished)

In [ ]:
%%sql
select emp_id,max(emp_salary) as max
from a

In [27]:
%%sql
select *,case when row_number() over(order by emp_id)%2 ==0 then "t" else"f" end  as rn
from a

StatementMeta(, cfe2aeb2-cbf6-436d-90a2-0f5a9304784e, 29, Finished, Available, Finished)

In [1]:
lst=[('alice',6),('bob',5),('Ram',10),('Lakshman',12),('Arjun',7),('Raghu',2)]
print(lst)
a=[i[1]  for i in lst]
b=max(a)
b=lst.index(b)
print(lst[b])
print(a)

max(lst,key=lambda x:x[1] )

StatementMeta(, a57feecc-59f4-4ce3-bf9d-7700347abe87, 3, Finished, Available, Finished)

StatementMeta(, a57feecc-59f4-4ce3-bf9d-7700347abe87, 5, Finished, Available, Finished)

[('alice', 6), ('bob', 5), ('Ram', 10), ('Lakshman', 12), ('Arjun', 7), ('Raghu', 2)]

In [32]:
%%sql
select *, first_value(emp_salary) over(order by emp_salary desc) as f
from a

StatementMeta(, cfe2aeb2-cbf6-436d-90a2-0f5a9304784e, 34, Finished, Available, Finished)

In [35]:
%%sql
select *, row_number() over(order by emp_salary desc) as f
select *, row_number() over(order by emp_salary desc) as f
from a

StatementMeta(, cfe2aeb2-cbf6-436d-90a2-0f5a9304784e, 37, Finished, Available, Finished)

In [49]:
%%sql
select *
,sum(emp_salary) over()   --rows between
,sum(emp_salary) over(order by emp_id)  ---- rrange
,sum(emp_salary) over(order by emp_salary)   ----range 
,sum(emp_salary) over(order by department)  ----range

-- ,sum(emp_salary) over(partition by department ),
-- sum(emp_salary) over(partition by department order by emp_id ),
--  sum(emp_salary) over(partition by department order by emp_id rows between 2 preceding and current row),
--  sum(emp_salary) over(partition by department order by emp_id rows between unbounded preceding and unbounded following)
from a

StatementMeta(, 99664508-2264-455d-b68f-d2975a21afbe, 51, Finished, Available, Finished)

In [27]:
%%sql
select emp_id,
--sum(emp_salary) over(partition by department ),
--sum(emp_salary) over(partition by department order by emp_id ),
 --sum(emp_salary) over(partition by department order by emp_id rows between 2 preceding and current row),
 sum(emp_id) over( order by emp_id rows between unbounded preceding and unbounded following),
 sum(emp_id) over( order by emp_id rows between unbounded preceding and current row),
 sum(emp_id) over( order by emp_id rows between 1 preceding and current row),
 sum(emp_id) over( order by emp_id rows between 1 preceding and 1 following),
 sum(emp_id) over( order by emp_id rows between 1 following and 2 following)
from a

StatementMeta(, 99664508-2264-455d-b68f-d2975a21afbe, 29, Finished, Available, Finished)

In [33]:
%%sql
select * 
from a
 order by emp_id

StatementMeta(, 99664508-2264-455d-b68f-d2975a21afbe, 35, Finished, Available, Finished)

In [34]:
#count nulls in all the columns
data = [(1, None, 'ab'),
        (2, 10, None),
        (None, None, 'cd')
        ]
columns = ['col1', 'col2', 'col3']
df = spark.createDataFrame(data, columns)
display(df)
df.createOrReplaceTempView("a")

StatementMeta(, 99664508-2264-455d-b68f-d2975a21afbe, 36, Finished, Available, Finished)

SynapseWidget(Synapse.DataFrame, 5de7e5fb-c272-4595-8516-e41ef88eeaaf)

In [43]:
%%sql 
select * 
from a
order by col1 desc nulls first

StatementMeta(, 99664508-2264-455d-b68f-d2975a21afbe, 45, Finished, Available, Finished)

In [42]:
data = [
    (101, "Aarav Mehta", 50000, "HR"),
    (102, "Priya Sharma", 51000, "HR"),
    (109, "Rohan Verma", 51000, "HR"),
    (104, "Neha Patel", 53000, "HR"),
    (104, "Ankit Singh", 70000, "IT"),
    (105, "Kavya Iyer", 72000, "IT"),
    (107, "Rahul Nair", 71000, "IT"),
    (108, "Sneha Reddy", 73000, "IT"),
    (109, "Vikram Desai", 60000, "Finance"),
    (110, "Isha Malhotra", 62000, "Finance"),
    (111, "Siddharth Rao", 61000, "Finance"),
    (112, "Pooja Das", 63000, "Finance"),
    (113, "Manish Joshi", 55000, "Marketing"),
    (114, "Tanya Kapoor", 57000, "Marketing"),
    (115, "Harsh Sinha", 56000, "Marketing"),
    (116, "Divya Jain", 58000, "Marketing")
]
 
columns = ["emp_id", "emp_name", "emp_salary", "department"]

df = spark.createDataFrame(data, schema=columns)
df.createOrReplaceTempView("a")

StatementMeta(, 1203c16f-40c5-4c3d-b995-ef160f1b854a, 45, Finished, Available, Finished)

In [6]:
%%sql 
select *
, sum(emp_id) over(order by emp_id range between 105 preceding and current row)
, sum(emp_salary) over(order by emp_id rows between 2 preceding and current row)
, sum(emp_salary) over(order by emp_id range between 2 preceding and current row)
from a

StatementMeta(, 1203c16f-40c5-4c3d-b995-ef160f1b854a, 8, Finished, Available, Finished)

In [58]:
%%sql
select  sum(emp_salary) from a
where emp_id between 109-2 and 109;

select sum(aa.emp_salary)
from (select emp_id, emp_salary
      from a
      order by emp_id
      limit 2+1
      offset 4-2-1) aa

StatementMeta(, 1203c16f-40c5-4c3d-b995-ef160f1b854a, 77, Finished, Available, Finished)

In [1]:
from pyspark.sql import Row
from pyspark.sql.functions import to_date

data= [
    Row(order_id=1001, customer_id="C001", order_date="2024-01-10", country="USA",  product="Laptop",quantity=2, price=700),
    Row(order_id=1002, customer_id="C002", order_date="2024-01-10", country="UK",   product="Phone", quantity=1, price=300),
    Row(order_id=1003, customer_id="C002", order_date="2024-01-11", country="UK",   product="Phone", quantity=1, price=300),
    Row(order_id=1004, customer_id="C003", order_date="2024-01-11", country="US",   product="Laptop",quantity=1, price=500),
    Row(order_id=1005, customer_id="C004", order_date="2024-01-12", country="NA",   product="Phone", quantity=1, price=300),
    Row(order_id=1006, customer_id="C004", order_date="2024-01-12", country="NA",   product="Laptop",quantity=1, price=500),
    Row(order_id=1008, customer_id="C005", order_date="2024-01-14", country="CH",   product="Phone", quantity=1, price=500),
    Row(order_id=1009, customer_id="C005", order_date="2024-01-14", country="CH",   product="Phone", quantity=1, price=500),
    Row(order_id=1010, customer_id="C002", order_date="2024-01-17", country="CH",   product="Phone", quantity=1, price=500),
    Row(order_id=1011, customer_id="C003", order_date="2024-01-17", country="CH",   product="Phone", quantity=1, price=500),
    Row(order_id=1012, customer_id="C001", order_date="2024-01-20", country="CH",   product="Phone", quantity=1, price=500)    
    ]
df = spark.createDataFrame(data)
display(df)
df.printSchema()
df.createOrReplaceTempView("a")

StatementMeta(, 0e4352fe-e3a8-465b-94f8-87860c7565d9, 3, Finished, Available, Finished)

Cache file does not exists. resource=$ml, path=$/nfs4/tridenttokenlibrary/tokens/ml.token
failed to get ml token
Traceback (most recent call last):
  File "/home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages/synapse/ml/fabric/token_utils.py", line 156, in _get_access_token_from_token_lib
    return PyTridentTokenLibrary.get_access_token_from_cache(resource)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages/trident_token_library_wrapper.py", line 71, in get_access_token_from_cache
    raise IOError(err_msg)
OSError: Cache file does not exists. resource=$ml, path=$/nfs4/tridenttokenlibrary/tokens/ml.token

SynapseWidget(Synapse.DataFrame, 8973c813-3556-43e8-99e4-efa3f05664e4)

root
 |-- order_id: long (nullable = true)
 |-- customer_id: string (nullable = true)
 |-- order_date: string (nullable = true)
 |-- country: string (nullable = true)
 |-- product: string (nullable = true)
 |-- quantity: long (nullable = true)
 |-- price: long (nullable = true)

In [3]:
%%sql
select to_date(order_date, "yyyy-MM-dd") as order_date
,EOMONTH(to_date(order_date, "yyyy-MM-dd"))
from a

StatementMeta(, 0e4352fe-e3a8-465b-94f8-87860c7565d9, 5, Finished, Available, Finished)

Error: [UNRESOLVED_ROUTINE] Cannot resolve function `EOMONTH` on search path [`system`.`builtin`, `system`.`session`, `spark_catalog`.`testlh`].; line 2 pos 1

In [ ]:
df = df.withColumn("order_date", to_date("order_date", "yyyy-MM-dd"))
display(df)

In [39]:
df.createOrReplaceTempView("b")

StatementMeta(, 1203c16f-40c5-4c3d-b995-ef160f1b854a, 41, Finished, Available, Finished)

In [ ]:
%%sql

select order_date, price
,sum(price) over( order by order_date rows between 2 preceding and current row) as rows
,sum(price) over( order by order_date range between 2 preceding and current row) as range
from b

In [24]:
%%sql
with 
aaa (select    country
            , sum(price) as totall
            , sum(price) filter(where product=="Phone") as phone_total
            , sum(price) filter(where product=="Laptop") as laptop_total
    from a
    group by country)

select 
    count(*) filter( where totall is null)+
    count(*) filter( where phone_total is null)+
    count(*) filter( where laptop_total is null)
from aaa

StatementMeta(, 81ec9ac6-09d7-4e7b-9352-1d7d0bc6638e, 26, Finished, Available, Finished)

In [13]:
%%sql
select    country
        , sum(price) as total
        
from a
where product=="Phone" 
group by country

StatementMeta(, 81ec9ac6-09d7-4e7b-9352-1d7d0bc6638e, 15, Finished, Available, Finished)

In [34]:
%%sql
select    array_agg(distinct country) filter(where country ! in  ("US","UK"))
from a

StatementMeta(, 81ec9ac6-09d7-4e7b-9352-1d7d0bc6638e, 36, Finished, Available, Finished)